/*
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.clockwork.openai.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.clockwork.openai.model.CreateClassificationResponseSelectedExamples;
/**
 * CreateClassificationResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-24T16:11:32.543455-05:00[America/Chicago]")

public class CreateClassificationResponse {
  @SerializedName("object")
  private String object = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("search_model")
  private String searchModel = null;

  @SerializedName("completion")
  private String completion = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("selected_examples")
  private List<CreateClassificationResponseSelectedExamples> selectedExamples = null;

  public CreateClassificationResponse object(String object) {
    this.object = object;
    return this;
  }

   /**
   * Get object
   * @return object
  **/
  @Schema(description = "")
  public String getObject() {
    return object;
  }

  public void setObject(String object) {
    this.object = object;
  }

  public CreateClassificationResponse model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @Schema(description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public CreateClassificationResponse searchModel(String searchModel) {
    this.searchModel = searchModel;
    return this;
  }

   /**
   * Get searchModel
   * @return searchModel
  **/
  @Schema(description = "")
  public String getSearchModel() {
    return searchModel;
  }

  public void setSearchModel(String searchModel) {
    this.searchModel = searchModel;
  }

  public CreateClassificationResponse completion(String completion) {
    this.completion = completion;
    return this;
  }

   /**
   * Get completion
   * @return completion
  **/
  @Schema(description = "")
  public String getCompletion() {
    return completion;
  }

  public void setCompletion(String completion) {
    this.completion = completion;
  }

  public CreateClassificationResponse label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public CreateClassificationResponse selectedExamples(List<CreateClassificationResponseSelectedExamples> selectedExamples) {
    this.selectedExamples = selectedExamples;
    return this;
  }

  public CreateClassificationResponse addSelectedExamplesItem(CreateClassificationResponseSelectedExamples selectedExamplesItem) {
    if (this.selectedExamples == null) {
      this.selectedExamples = new ArrayList<CreateClassificationResponseSelectedExamples>();
    }
    this.selectedExamples.add(selectedExamplesItem);
    return this;
  }

   /**
   * Get selectedExamples
   * @return selectedExamples
  **/
  @Schema(description = "")
  public List<CreateClassificationResponseSelectedExamples> getSelectedExamples() {
    return selectedExamples;
  }

  public void setSelectedExamples(List<CreateClassificationResponseSelectedExamples> selectedExamples) {
    this.selectedExamples = selectedExamples;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateClassificationResponse createClassificationResponse = (CreateClassificationResponse) o;
    return Objects.equals(this.object, createClassificationResponse.object) &&
        Objects.equals(this.model, createClassificationResponse.model) &&
        Objects.equals(this.searchModel, createClassificationResponse.searchModel) &&
        Objects.equals(this.completion, createClassificationResponse.completion) &&
        Objects.equals(this.label, createClassificationResponse.label) &&
        Objects.equals(this.selectedExamples, createClassificationResponse.selectedExamples);
  }

  @Override
  public int hashCode() {
    return Objects.hash(object, model, searchModel, completion, label, selectedExamples);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateClassificationResponse {\n");
    
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    searchModel: ").append(toIndentedString(searchModel)).append("\n");
    sb.append("    completion: ").append(toIndentedString(completion)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    selectedExamples: ").append(toIndentedString(selectedExamples)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
